from enum import Enum
from values.ConstValues import *


class Areas(Enum):
    TabPanel = (START_X_TP, END_X_TP, START_Y_TP, END_Y_TP, WIDTH_TP, HEIGHT_TP, COLOR_BACKGROUND_TOP_RGB)
    MainPanel = (START_X_MP, END_X_MP, START_Y_MP, END_Y_MP, WIDTH_MP, HEIGHT_MP, COLOR_BACKGROUND_MAIN_RGB)
    LeftPanel = (START_X_LP, END_X_LP, START_Y_LP, END_Y_LP, WIDTH_LP, HEIGHT_LP, COLOR_BACKGROUND_LEFT_RGB)
    ButtonsPanel = (START_X_PANEL_BUTTONS, END_X_PANEL_BUTTONS, START_Y_PANEL_BUTTONS, END_Y_PANEL_BUTTONS,
                    WIDTH_PANEL_BUTTONS, HEIGHT_PANEL_BUTTONS, COLOR_BACKGROUND_TOP_RGB)
    App = (0, WIDTH - 1, 0, HEIGHT - 1, WIDTH, HEIGHT, COLOR_BACKGROUND_DEFAULT)
