MAX_WIDTH = 800
MAX_HEIGHT = 600
MIN_WIDTH = MAX_WIDTH
MIN_HEIGHT = MAX_HEIGHT
HEIGHT = MAX_HEIGHT
WIDTH = MAX_WIDTH
TITLE = "Файлики и папочки"

MARGIN_BUTTON_HISTORY = 5
START_Y_BUTTON_HISTORY = MARGIN_BUTTON_HISTORY
START_X_BUTTON_HISTORY = MARGIN_BUTTON_HISTORY

# TP (TabPanel) - верхняя панель для вкладок
# MP (MainPanel) - панель для файлов и папок
# LP (LeftPanel) - левая панель

START_Y_TP = 5
END_Y_TP = 30
START_Y_MP = END_Y_TP
START_Y_LP = END_Y_TP
END_Y_LP = HEIGHT
START_X_LP = 0
END_X_LP = 180
START_X_MP = END_X_LP
END_X_MP = WIDTH

END_X_TP = WIDTH
END_Y_MP = HEIGHT


HEIGHT_TP = END_Y_TP - START_Y_TP

WIDTH_HISTORY_BUTTON = HEIGHT_TP
HEIGHT_HISTORY_BUTTON = WIDTH_HISTORY_BUTTON
WIDTH_ALL_BUTTON_HISTORY = START_X_BUTTON_HISTORY + 2 * WIDTH_HISTORY_BUTTON + MARGIN_BUTTON_HISTORY

START_X_TP = WIDTH_ALL_BUTTON_HISTORY

WIDTH_TP = END_X_TP - START_X_TP

WIDTH_LP = END_X_LP - START_X_LP
HEIGHT_LP = END_Y_LP - START_Y_LP

WIDTH_MP = END_X_MP - START_X_MP
HEIGHT_MP = END_Y_MP - START_Y_MP


WIDTH_ITEM = 93
HEIGHT_ITEM = 95
MARGIN_ITEM = 10
WIDTH_ICON = 50
HEIGHT_ICON = WIDTH_ICON
WIDTH_TEXT = WIDTH_ITEM
HEIGHT_TEXT = HEIGHT_ITEM - HEIGHT_ICON
MAX_LINE_TEXT = 12

FONT_SIZE = 10

ANGLE_WHEEL_TO_PX = 0.3
